version: '3'
services:
  signer:
    ports:
    - "5190:5190"
    image: ognerezov/aws-signer
    environment:
    - AWS_DEFAULT_REGION=your aws region
    - APP_SECRET=your secret
    - DISTRIBUTION=your distribtuion
    - LINK_TTL=3600000
    - TTL_SAFE_PERIOD=10
    - PUBLIC_KEY_ID=you public key id given by AWS
    - |
      PRIVATE_KEY=
      -----BEGIN RSA PRIVATE KEY-----
      your private key content
      your private key content
      your private key content
      -----END RSA PRIVATE KEY-----